[project]
name = "py-jsonl-ipc"
version = "0.0.25"
description = "Lightweight JSONL-based IPC using Python"
readme = "README.md"
requires-python = ">=3.13.5"
dependencies = [
    "pytest>=9.0.1",
    "setuptools>=80.9.0",
]
